language: c
sudo: required
before_install:
   - rvm install 2.2.1
install: gem install github-pages && wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-mirage.sh
before_script: jekyll build && cd _mirage
script: bash -ex ../.travis-mirage.sh
env:
  - OCAML_VERSION=4.03 MIRAGE_BACKEND=xen MIRAGE_NET=socket DEPLOY=0 FORK_USER=caindy
os:
  - linux