language: c
sudo: required
before_install:
  - rvm install 2.2
  - sudo apt-get -qq update
  - sudo apt-get -y install python-pip
install:
  - gem install github-pages
  - wget https://raw.githubusercontent.com/caindy/ocaml-ci-scripts/master/.travis-mirage.sh
  - pip install --user awscli
before_script:
  - jekyll build
  - cd _mirage
script:
  - bash -ex ../.travis-mirage.sh
  - S3FILENAME=`date '+%Y-%m-%d-%H-%M-%s.xen'`; aws s3 cp mir-www.xen "s3://mirage-blog/${FILENAME}"
  - aws ec2 run-instances --user-data file://ec2.sh --instance-type t2.nano --dry-run
env:
  - OCAML_VERSION=4.03 MIRAGE_BACKEND=xen DEPLOY=0 FORK_USER=caindy UPDATE_GCC_BINUTILS=1
os:
  - linux
